# Generated by Django 6.0.6 on 2026-06-17 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('service_type', models.CharField(choices=[('web_design', 'طراحی وبسایت'), ('seo', 'سئو و بهینه\u200cسازی'), ('course', 'دوره آموزشی'), ('consulting', 'مشاوره دیجیتال')], max_length=20, verbose_name='نوع خدمات')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='نام پدر')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی')),
                ('shenasname_no', models.CharField(blank=True, max_length=20, verbose_name='شماره شناسنامه')),
                ('shenasname_place', models.CharField(blank=True, max_length=100, verbose_name='محل صدور شناسنامه')),
                ('education_level', models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('bachelor', 'لیسانس'), ('master', 'فوق لیسانس'), ('phd', 'دکترا'), ('other', 'سایر')], max_length=20, verbose_name='آخرین مدرک تحصیلی')),
                ('major', models.CharField(blank=True, max_length=150, verbose_name='رشته تحصیلی')),
                ('domain', models.CharField(blank=True, choices=[('python-django', 'Python / Django'), ('htmlcssjs', 'HTML / CSS / JS'), ('ai', 'AI / هوش مصنوعی'), ('laravel', 'PHP / Laravel')], max_length=20, verbose_name='حوزه تخصصی')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=15, unique=True, verbose_name='تلفن همراه')),
                ('registration_date', models.CharField(max_length=20, verbose_name='تاریخ ثبت نام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('contacted', 'تماس گرفته شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_old', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام دوره',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای دوره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='شماره تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
