# Generated by Django 6.0.6 on 2026-06-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='user',
        ),
    ]
