# Generated by Django 6.0.6 on 2026-06-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_courseregistration_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregistration',
            old_name='domain',
            new_name='domains',
        ),
    ]
