# Generated by Django 6.0.6 on 2026-06-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_domain_courseregistration_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='domains',
            field=models.CharField(blank=True, max_length=20, verbose_name='حوزه تخصصی'),
        ),
    ]
