# Generated by Django 6.0.6 on 2026-06-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_courseregistration_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('request_date', models.CharField(max_length=20, verbose_name='تاریخ درخواست')),
                ('service_type', models.CharField(choices=[('class', 'ثبت\u200cنام کلاس'), ('website', 'طراحی سایت')], default='class', max_length=20, verbose_name='نوع خدمات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('contacted', 'تماس گرفته شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'درخواست طراحی سایت',
                'verbose_name_plural': 'درخواست\u200cهای طراحی سایت',
                'ordering': ['-created_at'],
            },
        ),
    ]
