# Generated by Django 6.0.6 on 2026-06-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_websiterequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiterequest',
            old_name='last_name',
            new_name='full_name',
        ),
    ]
