# Generated by Django 6.0.6 on 2026-06-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_last_name_websiterequest_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='loginmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'لاگین', 'verbose_name_plural': 'لاگین ها'},
        ),
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'کد تایید', 'verbose_name_plural': 'کد های تایید'},
        ),
        migrations.AlterModelOptions(
            name='websiterequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست مشاوره', 'verbose_name_plural': 'درخواست\u200cهای مشاوره'},
        ),
        migrations.RemoveField(
            model_name='websiterequest',
            name='request_date',
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='day',
            field=models.CharField(choices=[('today', 'امروز'), ('tomorrow', 'فردا'), ('thisweek', 'این هفته')], default='today', max_length=20, verbose_name='روز تماس'),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'صبح (9 تا 11)'), ('noon', 'ظهر (11 تا 13)'), ('afternoon', 'بعد از ظهر (13 تا 15)'), ('evening', 'شب (15 تا 19)')], default='morning', max_length=20, verbose_name='بازه ساعتی'),
        ),
        migrations.AlterField(
            model_name='websiterequest',
            name='service_type',
            field=models.CharField(choices=[('school', 'آموزشگاه'), ('webdesign', 'طراحی سایت')], default='class', max_length=20, verbose_name='نوع خدمات'),
        ),
    ]
