# Generated by Django 6.0.6 on 2026-06-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiterequest',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='websiterequest',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='websiterequest',
            name='service_type',
            field=models.CharField(choices=[('school', 'آموزشگاه'), ('webdesign', 'طراحی سایت')], default='school', max_length=20, verbose_name='نوع خدمات'),
        ),
    ]
