# Generated by Django 6.0.6 on 2026-06-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_websiterequest_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('service_type', models.CharField(choices=[('school', 'آموزشگاه'), ('webdesign', 'طراحی سایت')], default='school', max_length=20, verbose_name='نوع خدمات')),
                ('day', models.CharField(choices=[('today', 'امروز'), ('tomorrow', 'فردا'), ('thisweek', 'این هفته')], max_length=20, verbose_name='روز تماس')),
                ('time_slot', models.CharField(choices=[('morning', 'صبح (9 تا 11)'), ('noon', 'ظهر (11 تا 13)'), ('afternoon', 'عصر (13 تا 15)'), ('evening', 'شب (15 تا 17)')], max_length=20, verbose_name='بازه ساعتی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('contacted', 'تماس گرفته شده'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'درخواست تماس',
                'verbose_name_plural': 'درخواست\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='WebsiteRequest',
        ),
    ]
