# Generated by Django 6.0.6 on 2026-06-19 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educate', '0002_course_discount_percent_course_teacher_and_more'),
        ('users', '0009_contactrequest_delete_websiterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست مشاوره', 'verbose_name_plural': 'درخواست\u200cهای مشاوره'},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('membership', models.CharField(choices=[('free', 'رایگان'), ('gold', 'طلایی'), ('platinum', 'پلاتینیوم')], default='free', max_length=20, verbose_name='نوع اشتراک')),
                ('courses_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دوره\u200cها')),
                ('tickets_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تیکت\u200cها')),
                ('projects_count', models.PositiveIntegerField(default=0, verbose_name='تعداد پروژه\u200cها')),
                ('total_payments', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مجموع پرداخت\u200cها')),
                ('last_login_display', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('closed', 'بسته')], default='open', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(default='normal', max_length=20, verbose_name='اولویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('type', models.CharField(choices=[('deposit', 'شارژ'), ('payment', 'پرداخت'), ('refund', 'بازگشت')], max_length=20, verbose_name='نوع')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='پیشرفت')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educate.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='امتیاز')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educate.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
