# Generated by Django 6.0.6 on 2026-06-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_contactrequest_options_userprofile_userticket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'ordering': ['-registered_at'], 'verbose_name': 'کلاس کابر', 'verbose_name_plural': 'کلاس های کاربر'},
        ),
        migrations.AlterModelOptions(
            name='userreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر کابر', 'verbose_name_plural': 'نظزات کاربر'},
        ),
        migrations.AlterModelOptions(
            name='userticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'تیکت کابر', 'verbose_name_plural': 'تیکت های کابر'},
        ),
        migrations.AlterModelOptions(
            name='usertransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش کابر', 'verbose_name_plural': 'تراکنش های کابر'},
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userreview',
            unique_together=set(),
        ),
    ]
