# Generated by Django 6.0.6 on 2026-06-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_usercourse_options_alter_userreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'ordering': ['-registered_at'], 'verbose_name': 'کلاس کابر', 'verbose_name_plural': 'کلاس های کاربران'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل کاربران'},
        ),
        migrations.AlterModelOptions(
            name='userreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر کابر', 'verbose_name_plural': 'نظزات کاربران'},
        ),
        migrations.AlterModelOptions(
            name='userticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'تیکت کابر', 'verbose_name_plural': 'تیکت های کابران'},
        ),
        migrations.AlterModelOptions(
            name='usertransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش کابر', 'verbose_name_plural': 'تراکنش های کابران'},
        ),
    ]
