# Generated by Django 6.0.6 on 2026-06-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_category_tag_alter_usercourse_options_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ai', 'هوش مصنوعی'), ('web', 'طراحی سایت'), ('seo', 'SEO')], max_length=50, unique=True, verbose_name='نام دسته'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
