# Generated by Django 6.0.6 on 2026-06-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_category_icon_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی کیف پول'),
        ),
    ]
