# Generated by Django 6.0.6 on 2026-06-22 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educate', '0003_course_is_paid_course_plan_type_courseorder'),
        ('users', '0016_userprofile_wallet_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'ordering': ['-registered_at'], 'verbose_name': 'دوره کاربر', 'verbose_name_plural': 'دوره\u200cهای کاربران'},
        ),
        migrations.AddField(
            model_name='usercourse',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_courses', to='educate.courseorder', verbose_name='سفارش مرتبط'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت'),
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'course')},
        ),
    ]
