# Generated by Django 6.0.6 on 2026-06-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educate', '0003_course_is_paid_course_plan_type_courseorder'),
        ('users', '0017_alter_usercourse_options_usercourse_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educate.course'),
        ),
    ]
