# Generated by Django 6.0.6 on 2026-06-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_usercourse_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together=set(),
        ),
    ]
