# Generated by Django 6.0.6 on 2026-06-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_usercourse_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together=set(),
        ),
    ]
