# Generated by Django 6.0.6 on 2026-06-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='یادداشت ادمین'),
        ),
    ]
