# Generated by Django 6.0.6 on 2026-06-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_collaboration_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='message',
            field=models.TextField(blank=True, verbose_name='پیام تکمیلی'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='source',
            field=models.CharField(choices=[('landing', 'لندینگ'), ('work_with_us', 'صفحه همکاری با ما')], default='landing', max_length=20, verbose_name='منبع'),
        ),
    ]
