# Generated by Django 6.0.6 on 2026-07-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_collaboration_message_collaboration_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='service_type',
            field=models.CharField(choices=[('web_design', 'طراحی و توسعه وب\u200cسایت'), ('digital_marketing', 'دیجیتال مارکتینگ'), ('branding', 'برندینگ و خلاقیت'), ('seo', 'سئو و بهینه\u200cسازی'), ('consulting', 'مشاوره دیجیتال')], max_length=20, verbose_name='نوع خدمات'),
        ),
    ]
