# Generated by Django 6.0.6 on 2026-07-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ai', 'هوش مصنوعی'), ('web', 'طراحی UI/UX'), ('seo', 'سئو')], max_length=50, unique=True, verbose_name='نام دسته'),
        ),
    ]
