# Generated by Django 6.0.6 on 2026-08-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ai', 'هوش مصنوعی'), ('web', ' UI/UX طراحی '), ('webdevelopment', 'طراحی سایت'), ('marketing', 'دیجیتال مارکتینگ'), ('work', 'کسب و کار'), ('wordpress', 'وردپرس'), ('teach', 'آموزش'), ('seo', 'سئو')], max_length=50, unique=True, verbose_name='نام دسته'),
        ),
    ]
