# Generated by Django 6.0.6 on 2026-08-05 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='resume_file',
            field=models.FileField(blank=True, help_text='فایل\u200cهای PDF، Word یا TXT (اختیاری)', null=True, upload_to='collaborations/resumes/%Y/%m/', verbose_name='فایل رزومه'),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
