# Generated by Django 6.0.6 on 2026-08-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_collaboration_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='source',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='portfolio',
            field=models.URLField(blank=True, null=True, verbose_name='نمونه کار'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='work_chioces',
            field=models.CharField(blank=True, choices=[('frontend', 'توسعه دهنده فرانت اند'), ('backend', 'توسعه دهنده بک اند'), ('fullstack', 'فول استک'), ('UI/UX', 'طراح UI/UX')], max_length=20, null=True, verbose_name='موقعیت شغلی'),
        ),
    ]
