# Generated by Django 6.0.6 on 2026-08-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_collaboration_source_collaboration_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='user',
        ),
    ]
