# Generated by Django 6.0.6 on 2026-08-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_collaboration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='work_chioces',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='work_choices',
            field=models.CharField(blank=True, choices=[('frontend', 'توسعه دهنده فرانت اند'), ('backend', 'توسعه دهنده بک اند'), ('fullstack', 'فول استک'), ('designer', 'طراح UI/UX')], max_length=20, null=True, verbose_name='موقعیت شغلی'),
        ),
    ]
