# Generated by Django 6.0.6 on 2026-08-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_collaboration_work_chioces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='day',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='phone_or_email',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس یا ابمیل'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='project_choices',
            field=models.CharField(blank=True, choices=[('company', 'سایت شرکتی'), ('store', 'سایت فروشگاهی'), ('personal', 'سایت شخصی')], max_length=40, null=True, verbose_name='نوع پروژه'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='work_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت'),
        ),
    ]
