# Generated by Django 6.0.6 on 2026-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_contactrequest_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='phone_or_email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='شماره تماس یا ابمیل'),
        ),
    ]
