# Generated by Django 6.1 on 2026-08-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_contactrequest_phone_or_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone_or_email', models.CharField(blank=True, max_length=150, null=True, verbose_name='شماره تماس یا ابمیل')),
                ('grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='تحصیلات')),
                ('study_choices', models.CharField(blank=True, choices=[('ai', 'ai'), ('backend', 'backend'), ('frontend', 'frontend'), ('seo', 'seo'), ('wordpress', 'wordpress'), ('ui/ux', 'ui/ux')], max_length=40, null=True, verbose_name='نوع کلاس')),
                ('message', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'درخواست دوره',
                'verbose_name_plural': 'درخواست\u200cهای دوره',
                'ordering': ['-created_at'],
            },
        ),
    ]
