# Generated by Django 6.1 on 2026-08-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_studyrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_at'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='users_artic_slug_bfb1e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='users_artic_categor_43c8ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='users_artic_publish_63f5b6_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(default='', verbose_name='url متعارف'),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت انتشار'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='article',
            name='schema',
            field=models.CharField(choices=[('article', 'مقاله'), ('blogposting', 'پست بلاگ'), ('product', 'محصول'), ('faq', 'سوالات متداول'), ('howto', 'آموزش گام به گام'), ('organization', 'سازمان'), ('localbusiness', 'کسب و کار محلی'), ('beadcrumb', 'مسیر ناوبری'), ('person', 'شخص'), ('review', 'نقد و بررسی')], default='article', max_length=50, verbose_name='نشانه گذاری'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('prepublish', 'پیش نمایس'), ('published', 'منتشر شده'), ('private', 'خصوصی'), ('timed', 'زمانبندی شده'), ('deleted', 'حذف شده')], default='prepublish', max_length=40, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tags/', verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=' blogs/', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tags/', verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='article',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
    ]
