# Generated by Django 6.0.5 on 2026-05-13 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='اسلاگ')),
                ('category', models.CharField(choices=[('fullstack', 'برنامه\u200cنویسی Full-Stack'), ('ui_ux', 'طراحی رابط کاربری (UI/UX)'), ('digital_business', 'مدیریت کسب و کار دیجیتال')], max_length=50, verbose_name='دسته\u200cبندی')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کامل')),
                ('practical_percentage', models.PositiveSmallIntegerField(default=70, verbose_name='درصد بخش عملی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='تصویر دوره')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('is_popular', models.BooleanField(default=True, verbose_name='دوره محبوب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ویژگی')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون (کلاس FontAwesome)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='educate.course')),
            ],
        ),
    ]
