# Generated by Django 6.0.6 on 2026-06-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educate', '0003_course_is_paid_course_plan_type_courseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='plan_type',
        ),
    ]
