# Generated by Django 6.0.6 on 2026-06-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educate', '0005_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('fullstack', 'برنامه\u200cنویسی Full-Stack'), ('ui_ux', 'طراحی رابط کاربری (UI/UX)'), ('digital_business', 'مدیریت کسب و کار دیجیتال')], max_length=50, null=True, verbose_name='دسته\u200cبندی'),
        ),
    ]
