# Generated by Django 6.0.6 on 2026-08-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educate', '0007_seosignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام کامل')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('educate', models.CharField(max_length=200, verbose_name='مقطع تحصیلی و زمینه فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ثبت نام سئو',
                'verbose_name_plural': 'ثبت نام های سئو',
                'ordering': ['-created_at'],
            },
        ),
    ]
