# Generated by Django 6.0.6 on 2026-08-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educate', '0009_backsignup_frontsignup_uisignup_wordpresssignup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aisignup',
            options={'ordering': ['-created_at'], 'verbose_name': 'ثبت نام هوش مصنوعی', 'verbose_name_plural': 'ثبت نام های هوش مصنوعی'},
        ),
        migrations.AlterModelOptions(
            name='backsignup',
            options={'ordering': ['-created_at'], 'verbose_name': 'ثبت نام بک اند', 'verbose_name_plural': 'ثبت نام های بک اند'},
        ),
        migrations.AlterModelOptions(
            name='frontsignup',
            options={'ordering': ['-created_at'], 'verbose_name': 'ثبت نام فرانت  اند', 'verbose_name_plural': 'ثبت نام های فرانت اند'},
        ),
        migrations.AlterModelOptions(
            name='uisignup',
            options={'ordering': ['-created_at'], 'verbose_name': 'ثبت نام UI', 'verbose_name_plural': 'ثبت نام های UI'},
        ),
        migrations.AlterModelOptions(
            name='wordpresssignup',
            options={'ordering': ['-created_at'], 'verbose_name': 'ثبت نام وردپرس', 'verbose_name_plural': 'ثبت نام های وردپرس'},
        ),
    ]
