# Generated by Django 6.0.6 on 2026-06-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_website', models.CharField(choices=[('has_domain', 'بله، سایت فعال دارم'), ('no_domain', 'خیر، اولین سایتم هست')], default='no_domain', max_length=20, verbose_name='آیا سایت داشته\u200cاید؟')),
                ('current_website_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس سایت فعلی')),
                ('goals', models.TextField(blank=True, verbose_name='اهداف')),
                ('business_field', models.CharField(blank=True, choices=[('education', 'آموزشی'), ('service', 'خدماتی'), ('tourism', 'گردشگری'), ('medical', 'پزشکی'), ('shop', 'فروشگاهی'), ('personal', 'شخصی'), ('news', 'خبری و رسانه ای'), ('industry', 'صنعتی')], max_length=50, verbose_name='حوزه کاری')),
                ('design_styles', models.TextField(blank=True, verbose_name='سبک طراحی')),
                ('selected_color', models.CharField(blank=True, max_length=50, verbose_name='رنگ انتخابی')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('raw_data', models.JSONField(default=dict, verbose_name='داده\u200cهای خام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_processed', models.BooleanField(default=False, verbose_name='پردازش شده')),
            ],
            options={
                'verbose_name': 'سفارش طراحی وبسایت',
                'verbose_name_plural': 'سفارش\u200cهای طراحی وبسایت',
                'ordering': ['-created_at'],
            },
        ),
    ]
