# Generated by Django 6.0.6 on 2026-06-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteorder',
            name='business_field',
            field=models.CharField(blank=True, choices=[('آموزشی', 'آموزشی'), ('خدماتی', 'خدماتی'), ('گردشگری', 'گردشگری'), ('پزشکی', 'پزشکی'), ('فروشگاهی', 'فروشگاهی'), ('شخصی', 'شخصی'), ('خبری و رسانه ای', 'خبری و رسانه ای'), ('صنعتی', 'صنعتی')], max_length=50, null=True, verbose_name='حوزه کاری'),
        ),
    ]
