# Generated by Django 6.0.6 on 2026-06-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_websiteorder_business_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteorder',
            name='business_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='حوزه کاری'),
        ),
    ]
