# Generated by Django 6.0.6 on 2026-06-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_websiteorder_business_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان قالب')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت تومان')),
                ('discounted_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='درصد تخفیف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='templates/', verbose_name='تصویر')),
                ('desctop_image', models.ImageField(blank=True, null=True, upload_to='templates/desktop/', verbose_name='تصویر دسکتاپ')),
                ('tablet_image', models.ImageField(blank=True, null=True, upload_to='templates/tablet/', verbose_name='تصویر تبلت')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='templates/mobile/', verbose_name='تصویر موبایل')),
                ('desctop_section', models.JSONField(blank=True, default=list, verbose_name='بخش\u200cهای دسکتاپ')),
                ('tablet_section', models.JSONField(blank=True, default=list, verbose_name='بخش\u200cهای تبلت')),
                ('mobile_section', models.JSONField(blank=True, default=list, verbose_name='بخش\u200cهای موبایل')),
                ('is_popular', models.BooleanField(default=False, verbose_name='محبوب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'قالب',
                'verbose_name_plural': 'قالب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
