# Generated by Django 6.0.6 on 2026-06-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_websiteorder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='desctop_image',
            new_name='desktop_image',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='desctop_section',
            new_name='desktop_sections',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='mobile_section',
            new_name='mobile_sections',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='tablet_section',
            new_name='tablet_sections',
        ),
        migrations.RemoveField(
            model_name='template',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='template',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='template',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت (تومان)'),
        ),
    ]
