# Generated by Django 6.0.6 on 2026-06-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_desctop_image_template_desktop_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='desktop_sections',
            field=models.JSONField(blank=True, default=list, help_text='آدرس تصاویر بخش\u200cهای مختلف: ["/media/section1.jpg", "/media/section2.jpg"]', verbose_name='بخش\u200cهای دسکتاپ'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_sections',
            field=models.JSONField(blank=True, default=list, help_text='آدرس تصاویر بخش\u200cهای مختلف: ["/media/mobile1.jpg", "/media/mobile2.jpg"]', verbose_name='بخش\u200cهای موبایل'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_sections',
            field=models.JSONField(blank=True, default=list, help_text='آدرس تصاویر بخش\u200cهای مختلف: ["/media/tablet1.jpg", "/media/tablet2.jpg"]', verbose_name='بخش\u200cهای تبلت'),
        ),
    ]
