# Generated by Django 6.0.6 on 2026-06-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_template_desktop_sections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='desktop_sections',
        ),
        migrations.RemoveField(
            model_name='template',
            name='mobile_sections',
        ),
        migrations.RemoveField(
            model_name='template',
            name='tablet_sections',
        ),
        migrations.AddField(
            model_name='template',
            name='desktop_about',
            field=models.ImageField(blank=True, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - درباره ما'),
        ),
        migrations.AddField(
            model_name='template',
            name='desktop_contact',
            field=models.ImageField(blank=True, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - فرم تماس'),
        ),
        migrations.AddField(
            model_name='template',
            name='desktop_footer',
            field=models.ImageField(blank=True, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - فوتر سایت'),
        ),
        migrations.AddField(
            model_name='template',
            name='desktop_home',
            field=models.ImageField(blank=True, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='template',
            name='desktop_menu',
            field=models.ImageField(blank=True, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - منوی موبایل'),
        ),
        migrations.AddField(
            model_name='template',
            name='desktop_products',
            field=models.ImageField(blank=True, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - صفحه محصولات'),
        ),
        migrations.AddField(
            model_name='template',
            name='desktop_reviews',
            field=models.ImageField(blank=True, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - بخش نظرات'),
        ),
        migrations.AddField(
            model_name='template',
            name='mobile_about',
            field=models.ImageField(blank=True, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - درباره ما'),
        ),
        migrations.AddField(
            model_name='template',
            name='mobile_contact',
            field=models.ImageField(blank=True, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - فرم تماس'),
        ),
        migrations.AddField(
            model_name='template',
            name='mobile_footer',
            field=models.ImageField(blank=True, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - فوتر سایت'),
        ),
        migrations.AddField(
            model_name='template',
            name='mobile_home',
            field=models.ImageField(blank=True, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='template',
            name='mobile_menu',
            field=models.ImageField(blank=True, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - منوی موبایل'),
        ),
        migrations.AddField(
            model_name='template',
            name='mobile_products',
            field=models.ImageField(blank=True, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - صفحه محصولات'),
        ),
        migrations.AddField(
            model_name='template',
            name='mobile_reviews',
            field=models.ImageField(blank=True, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - بخش نظرات'),
        ),
        migrations.AddField(
            model_name='template',
            name='tablet_about',
            field=models.ImageField(blank=True, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - درباره ما'),
        ),
        migrations.AddField(
            model_name='template',
            name='tablet_contact',
            field=models.ImageField(blank=True, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - فرم تماس'),
        ),
        migrations.AddField(
            model_name='template',
            name='tablet_footer',
            field=models.ImageField(blank=True, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - فوتر سایت'),
        ),
        migrations.AddField(
            model_name='template',
            name='tablet_home',
            field=models.ImageField(blank=True, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='template',
            name='tablet_menu',
            field=models.ImageField(blank=True, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - منوی موبایل'),
        ),
        migrations.AddField(
            model_name='template',
            name='tablet_products',
            field=models.ImageField(blank=True, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - صفحه محصولات'),
        ),
        migrations.AddField(
            model_name='template',
            name='tablet_reviews',
            field=models.ImageField(blank=True, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - بخش نظرات'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/desktop/', verbose_name='تصویر اصلی دسکتاپ'),
        ),
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/', verbose_name='تصویر اصلی (کارت)'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/mobile/', verbose_name='تصویر اصلی موبایل'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/tablet/', verbose_name='تصویر اصلی تبلت'),
        ),
    ]
