# Generated by Django 6.0.6 on 2026-06-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_template_desktop_sections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='template',
            name='price',
        ),
    ]
