# Generated by Django 6.0.6 on 2026-06-21 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_template_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام طرح')),
                ('plan_type', models.CharField(choices=[('standard', 'استاندارد'), ('premium', 'پیشرفته'), ('professional', 'حرفه\u200cای')], max_length=20, unique=True, verbose_name='نوع')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('features', models.JSONField(default=list, verbose_name='ویژگی\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'طرح آماده',
                'verbose_name_plural': 'طرح\u200cهای آماده',
                'ordering': ['price'],
            },
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_about',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - درباره ما'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_contact',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - فرم تماس'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_footer',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - فوتر سایت'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_home',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/', verbose_name='تصویر اصلی دسکتاپ'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_menu',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - منوی موبایل'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_products',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - صفحه محصولات'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_reviews',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - بخش نظرات'),
        ),
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/', verbose_name='تصویر اصلی (کارت)'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_about',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - درباره ما'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_contact',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - فرم تماس'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_footer',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - فوتر سایت'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_home',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/', verbose_name='تصویر اصلی موبایل'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_menu',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - منوی موبایل'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_products',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - صفحه محصولات'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_reviews',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - بخش نظرات'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_about',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - درباره ما'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_contact',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - فرم تماس'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_footer',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - فوتر سایت'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_home',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/', verbose_name='تصویر اصلی تبلت'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_menu',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - منوی موبایل'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_products',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - صفحه محصولات'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_reviews',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - بخش نظرات'),
        ),
        migrations.CreateModel(
            name='WebsitePlanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'پرداخت ناموفق'), ('processing', 'در حال اجرا'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('domain', models.CharField(blank=True, max_length=100, verbose_name='دامنه درخواستی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.websiteplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش طرح آماده',
                'verbose_name_plural': 'سفارش\u200cهای طرح\u200cهای آماده',
                'ordering': ['-created_at'],
            },
        ),
    ]
