# Generated by Django 6.0.6 on 2026-06-22 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_websiteplan_alter_template_desktop_about_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=20, verbose_name='نوع طرح')),
                ('plan_name', models.CharField(max_length=100, verbose_name='نام طرح')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'پرداخت ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش مستقیم',
                'verbose_name_plural': 'سفارش\u200cهای مستقیم',
                'ordering': ['-created_at'],
            },
        ),
    ]
