# Generated by Django 6.0.6 on 2026-06-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_directorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectOrder',
        ),
    ]
