# Generated by Django 6.0.6 on 2026-06-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_template_desktop_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='desktop_about',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - درباره ما'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_contact',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - فرم تماس'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_footer',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - فوتر سایت'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_home',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_menu',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - منوی موبایل'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_products',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - صفحه محصولات'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_reviews',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - بخش نظرات'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_about',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - درباره ما'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_contact',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - فرم تماس'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_footer',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - فوتر سایت'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_home',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_menu',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - منوی موبایل'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_products',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - صفحه محصولات'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_reviews',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - بخش نظرات'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_about',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - درباره ما'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_contact',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - فرم تماس'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_footer',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - فوتر سایت'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_home',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_menu',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - منوی موبایل'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_products',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - صفحه محصولات'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_reviews',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - بخش نظرات'),
        ),
    ]
