# Generated by Django 6.0.6 on 2026-06-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_template_desktop_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='desktop_contact',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ -  لاگین'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_footer',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ -  وبلاگ'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_menu',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ -  داشبورد'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_products',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - صفحه فروشگاه'),
        ),
        migrations.AlterField(
            model_name='template',
            name='desktop_reviews',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ -  سبد خرید'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_contact',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل -  لاگین'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_footer',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل -  وبلاگ'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_menu',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل -  داشبورد'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_products',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - صفحه فروشگاه'),
        ),
        migrations.AlterField(
            model_name='template',
            name='mobile_reviews',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل -  سبد خرید'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_contact',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت -  لاگین'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_footer',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت -  وبلاگ'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_menu',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت -  داشبورد'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_products',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - صفحه فروشگاه'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tablet_reviews',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت -  سبد خرید'),
        ),
    ]
