# Generated by Django 6.0.6 on 2026-06-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_template_desktop_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='desktop_products',
            new_name='desktop_store',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='mobile_products',
            new_name='mobile_store',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='tablet_products',
            new_name='tablet_store',
        ),
        migrations.RemoveField(
            model_name='template',
            name='desktop_contact',
        ),
        migrations.RemoveField(
            model_name='template',
            name='desktop_footer',
        ),
        migrations.RemoveField(
            model_name='template',
            name='desktop_menu',
        ),
        migrations.RemoveField(
            model_name='template',
            name='desktop_reviews',
        ),
        migrations.RemoveField(
            model_name='template',
            name='mobile_contact',
        ),
        migrations.RemoveField(
            model_name='template',
            name='mobile_footer',
        ),
        migrations.RemoveField(
            model_name='template',
            name='mobile_menu',
        ),
        migrations.RemoveField(
            model_name='template',
            name='mobile_reviews',
        ),
        migrations.RemoveField(
            model_name='template',
            name='tablet_contact',
        ),
        migrations.RemoveField(
            model_name='template',
            name='tablet_footer',
        ),
        migrations.RemoveField(
            model_name='template',
            name='tablet_menu',
        ),
        migrations.RemoveField(
            model_name='template',
            name='tablet_reviews',
        ),
        migrations.AddField(
            model_name='template',
            name='desktop_blog',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - وبلاگ'),
        ),
        migrations.AddField(
            model_name='template',
            name='desktop_cart',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - سبد خرید'),
        ),
        migrations.AddField(
            model_name='template',
            name='desktop_dash',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - داشبورد'),
        ),
        migrations.AddField(
            model_name='template',
            name='desktop_login',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/desktop/sections/', verbose_name='دسکتاپ - لاگین'),
        ),
        migrations.AddField(
            model_name='template',
            name='mobile_blog',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - وبلاگ'),
        ),
        migrations.AddField(
            model_name='template',
            name='mobile_cart',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - سبد خرید'),
        ),
        migrations.AddField(
            model_name='template',
            name='mobile_dash',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - داشبورد'),
        ),
        migrations.AddField(
            model_name='template',
            name='mobile_login',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/mobile/sections/', verbose_name='موبایل - لاگین'),
        ),
        migrations.AddField(
            model_name='template',
            name='tablet_blog',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - وبلاگ'),
        ),
        migrations.AddField(
            model_name='template',
            name='tablet_cart',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - سبد خرید'),
        ),
        migrations.AddField(
            model_name='template',
            name='tablet_dash',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - داشبورد'),
        ),
        migrations.AddField(
            model_name='template',
            name='tablet_login',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='templates/tablet/sections/', verbose_name='تبلت - لاگین'),
        ),
    ]
