# Generated by Django 6.0.6 on 2026-08-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_desktop_products_template_desktop_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('work_name', models.URLField(max_length=100, verbose_name='نام کسب و کار')),
                ('service_choices', models.CharField(choices=[('seo', 'سئو و گوگل ادز'), ('web', 'طراحی سایت'), ('management', 'مدیرت شبکه های اجتماعی'), ('consult', 'مشاوره برندینگ')], max_length=40, verbose_name='خدمت مورد نیاز')),
                ('message', models.TextField(verbose_name='توضیحات کوتاه')),
            ],
        ),
    ]
