# Generated by Django 6.0.6 on 2026-08-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_digitalmarketing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalmarketing',
            options={'ordering': ['-created_at'], 'verbose_name': 'مشاوره دیجیتال مارکتینگ', 'verbose_name_plural': 'مشاوره های دیجیتال مارکتینگ'},
        ),
        migrations.AddField(
            model_name='digitalmarketing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
