# Generated by Django 6.0.6 on 2026-08-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_digitalmarketing_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalmarketing',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
