# Generated by Django 6.0.6 on 2026-08-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_phone_number_digitalmarketing_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalmarketing',
            name='email',
        ),
    ]
