# Generated by Django 6.1 on 2026-08-16 20:59

import django.db.models.deletion
import myadmin.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0020_remove_digitalmarketing_email'),
        ('users', '0037_alter_article_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=100, verbose_name='عنوان سایت')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='شعار')),
                ('site_url', models.URLField(verbose_name='آدرس سایت (URL)')),
                ('wordpress_url', models.URLField(blank=True, verbose_name='آدرس وردپرس (URL)')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='ایمیل مدیر')),
                ('allow_registration', models.BooleanField(default=False, verbose_name='اجازه ثبت\u200cنام به کاربران جدید')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'عربی')], default='fa', max_length=10, verbose_name='زبان سایت')),
                ('timezone', models.CharField(choices=[('Asia/Tehran', 'تهران'), ('Asia/Dubai', 'دبی'), ('Europe/Berlin', 'برلین'), ('UTC', 'UTC')], default='Asia/Tehran', max_length=50, verbose_name='منطقه زمانی')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon سایت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='نام مهمان')),
                ('object_id', models.PositiveIntegerField()),
                ('body', models.TextField(verbose_name='نوشته')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بازبینی'), ('approved', 'تأیید شده'), ('spam', 'هرزنامه')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بازبینی')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پوشه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myadmin.mediafolder')),
            ],
            options={
                'verbose_name': 'پوشه رسانه',
                'verbose_name_plural': 'پوشه\u200cهای رسانه',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان')),
                ('file', models.FileField(upload_to=myadmin.models.media_upload_path, verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو'), ('pdf', 'پی\u200cدی\u200cاف'), ('other', 'سایر')], editable=False, max_length=10, verbose_name='نوع فایل')),
                ('size', models.PositiveIntegerField(default=0, editable=False, verbose_name='حجم (بایت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلود کننده')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='myadmin.mediafolder', verbose_name='پوشه')),
            ],
            options={
                'verbose_name': 'فایل رسانه',
                'verbose_name_plural': 'کتابخانه رسانه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Writen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.category')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='shop.template')),
            ],
        ),
    ]
