# Generated by Django 6.1 on 2026-08-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_display', models.CharField(choices=[('latest_posts', 'آخرین نوشته\u200cها'), ('static_page', 'صفحه ثابت')], default='latest_posts', max_length=20, verbose_name='صفحه نخست نمایش می\u200cدهد')),
                ('posts_per_page', models.PositiveIntegerField(default=10, verbose_name='تعداد نوشته در هر صفحه')),
                ('allow_search_indexing', models.BooleanField(default=True, help_text='در صورت غیرفعال بودن، کل صفحات سایت از ایندکس گوگل و سایر موتورهای جستجو خارج می\u200cشوند.', verbose_name='قابلیت مشاهده برای موتورهای جستجو')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات خواندن',
                'verbose_name_plural': 'تنظیمات خواندن',
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_separator', models.CharField(choices=[('-', '- (خط تیره)'), ('|', '| (پایپ)'), ('•', '• (نقطه)'), (':', ': (دو نقطه)')], default='-', max_length=5, verbose_name='جداکننده عنوان')),
                ('homepage_title_template', models.CharField(max_length=255, verbose_name='قالب عنوان سئوی صفحه اصلی')),
                ('homepage_meta_description', models.TextField(help_text='حداکثر ۱۶۰ تا ۳۲۰ کاراکتر توصیه می\u200cشود.', max_length=320, verbose_name='توضیحات سئوی صفحه اصلی')),
                ('og_image', models.ImageField(blank=True, help_text='اندازه پیشنهادی ۱۲۰۰×۶۳۰ پیکسل', null=True, upload_to='seo/og/', verbose_name='تصویر پیش\u200cفرض اشتراک\u200cگذاری (OG Image)')),
                ('instagram_url', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='لینکدین')),
                ('sitemap_auto_generate', models.BooleanField(default=True, help_text='ساخت و به\u200cروزرسانی خودکار sitemap.xml', verbose_name='تولید خودکار XML Sitemap')),
                ('allow_search_indexing', models.BooleanField(default=True, help_text='در صورت غیرفعال بودن، کل سایت noindex می\u200cشود.', verbose_name='قابلیت مشاهده برای موتورهای جستجو')),
                ('robots_txt_content', models.TextField(blank=True, default='User-agent: *\nAllow: /\n', help_text='این متن فقط زمانی اعمال می\u200cشود که «قابلیت مشاهده» فعال باشد.', verbose_name='ویرایشگر Robots.txt')),
                ('schema_type', models.CharField(choices=[('Organization', 'سازمان (Organization)'), ('LocalBusiness', 'کسب\u200cوکار محلی (LocalBusiness)'), ('Person', 'شخص (Person)'), ('WebSite', 'وب\u200cسایت (WebSite)')], default='Organization', max_length=20, verbose_name='نوع Schema سازمان')),
                ('schema_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس سازمان')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سئو',
                'verbose_name_plural': 'تنظیمات سئو',
            },
        ),
    ]
